# -*- coding: utf-8 -*-
"""BOT_IA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jkuWsj24XIBnKkUbRue9STANDMO5USLV
"""

!unzip ./modelo.zip

import PIL
PIL.__version__
!pip install -q tf-keras==2.19.0 h5py==3.11.0
import tf_keras as keras  # Importando tf-keras – una versión de Keras compatible con modelos .h5
from tf_keras.models import load_model  # Importando la función load_model de tf_keras, que nos permite abrir el modelo
from PIL import Image, ImageOps  # Importar las clases Image e ImageOps de la biblioteca PIL
import numpy as np

def get_class(model_path, labels_path, image_path):
  np.set_printoptions(suppress=True)
  model = load_model(model_path, compile=False)
  class_names = open(labels_path, "r").readlines()
  data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

  image = Image.open(image_path).convert("RGB")

  size = (224, 224)
  image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)
  image_array = np.asarray(image)
  normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1
  data[0] = normalized_image_array
  prediction = model.predict(data)
  print(prediction)
  index = np.argmax(prediction)
  class_name = class_names[index]
  confidence_score = prediction[0][index]
  if confidence_score < 0.5:
    return "El modelo no puede dar una respuesta"
  else:
    return f"Objeto detectado: {class_name[2:]} Probabilidad: {confidence_score}"

!pip install discord

import discord
from discord.ext import commands
import nest_asyncio
nest_asyncio.apply()

intents = discord.Intents.default()
intents.message_content = True

bot = commands.Bot(command_prefix= "$", intents=intents)

@bot.event
async def on_ready():
    print(f'We have logged in as {bot.user}')

@bot.command()
async def hello(ctx):
    await ctx.send(f'Hi! I am a bot {bot.user}!')

@bot.command()
async def heh(ctx, count_heh = 5):
    await ctx.send("he" * count_heh)

@bot.command()
async def check(ctx):
    if ctx.message.attachments:
      for foto in ctx.message.attachments:
        file_name = foto.filename
        file_url = foto.url
        await foto.save(f"./{file_name}")
        await ctx.send("Foto guardada exitosamente.")
        await ctx.send(get_class(model_path="./keras_model.h5", labels_path="labels.txt", image_path=f"./{foto.filename}"))




    else:
      await ctx.send("Olvidaste subir una imagen.")

bot.run("Token")